# Generated by Django 4.2 on 2023-11-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_alter_preference_available_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='has_passport',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preference',
            name='salary_expectation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
